apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helloworld-deployment.yaml
- helloworld-namespace.yaml
- helloworld-service.yaml
- helloworld-virtual-service.yaml
- asm-controlplane-configmap.yaml
- asm-controlplane-revision.yaml
- istio-ingressgateway-deployment.yaml
- istio-ingressgateway-sds-role-binding.yaml
- istio-ingressgateway-sds-role.yaml
- istio-ingressgateway-service.yaml
- istio-ingress-namespace.yaml
- public-gateway.yaml

# Patch the Istio ingress service so that our IP is used.
patches:
- patch: |-
    - op: add
      path: /spec/loadBalancerIP
      value: 35.203.20.227
  target:
    kind: Service
    name: istio-ingressgateway
    namespace: istio-ingress
    version: v1
