apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helloworld
  name: helloworld
  namespace: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld
    spec:
      # Pod wide security settings:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        # seems to succeed only when specific uid/guid is set
        runAsNonRoot: true
      containers:
      - image: mikewilliamson/helloworld
        name: helloworld
        # Container specific security settings:
        securityContext:
          # No new privs for process or it's children
          # https://github.com/kubernetes/design-proposals-archive/blob/main/auth/no-new-privs.md
          allowPrivilegeEscalation: false
          # TODO: npm checks for updates and writes a file
          # Explore disabling check or removing npm
          # readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 300m
            memory: 150Mi
status: {}
